version: '3.8'

services:
  # 1. Фронтенд (Сайт) — как было изначально
  frontend:
    image: lari914/my-app:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  # 2. Бэкенд (Сервер приложений) — открываем порт 5000 обратно наружу
  backend:
    image: lari914/my-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - # Берем пароль для самой базы из .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=mydb
    depends_on:
      - database

  # 3. Официальная база данных — без изменений
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      # Берем пароль для бэкенда из .env (он совпадает с паролем базы)
      - DB_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
