server {
    listen 80;
    server_name localhost;

    # Отдаем ваши 4 HTML-страницы фронтенда
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Перенаправляем запросы, которые начинаются с /api/, на бэкенд
    location /api/ {
        # Слэш на конце backend:5000/ важен: он уберет слово "/api" из запроса к Node.js
        proxy_pass http://backend:5000/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
