name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # --- ЭТАП CI: Сборка в облаке GitHub и пуш на склад Docker Hub ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 1. Собираем и пушим ваш старый ФРОНТЕНД (сайт на Nginx)
    - name: Build and push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: lari914/my-app:latest

    # 2. Собираем и пушим новый БЭКЕНД (сервер на Node.js)
    - name: Build and push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: lari914/my-backend:latest

  # --- ЭТАП CD: Доставка и запуск прямо на твоей Fedora ---
  deploy:
    needs: build-and-push # Запускать CD только после того, как CI (сборка) завершится успехом
    runs-on: self-hosted  # Команды выполняет ваш агент-runner на Fedora
    steps:
    # Обязательный шаг! Агент должен скачать обновленный файл docker-compose.yml из Git
    - name: Checkout code on Fedora
      uses: actions/checkout@v4

    # Управляем всей системой через Docker Compose
    - name: Update Applications via Docker Compose
      run: |
        # 1. Скачиваем свежие образы фронтенда и бэкенда с Docker Hub
        sudo docker compose pull
        
        # 2. Перезапускаем контейнеры. Compose сам создаст сеть, обновит то, что изменилось,
        # и поднимет базу данных, если её ещё не было на сервере.
        sudo docker compose up -d --remove-orphans
        
        # 3. Чистим старые кэши и остановленные контейнеры, чтобы не забивать диск Fedora
        sudo docker image prune -f
